apiVersion: v1
baseDomain: example.com
metadata:
  name: ocp42
networking:
  machineCIDR: 192.168.107.0/24
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.107.6
    ingressVIP: 192.168.107.7
    dnsVIP: 192.168.107.8
    #libvirtURI:
    hosts:
      - name: master-0
        role: master
        bmc:
          address: ipmi://192.168.254.81
          username: root
          password: password
        bootMACAddress: AA:BB:CC:DD:EE:F1
        hardwareProfile: default
      - name: master-1
        role: master
        bmc:
          address: ipmi://192.168.254.82
          username: root
          password: password
        bootMACAddress: AA:BB:CC:DD:EE:F2
        hardwareProfile: default
      - name: master-2
        role: master
        bmc:
          address: ipmi://192.168.254.83
          username: root
          password: password
        bootMACAddress: AA:BB:CC:DD:EE:F3
        hardwareProfile: default
      - name: worker-0
       role: worker
       bmc:
         address: ipmi://192.168.254.84
         username: admin
         password: password
       bootMACAddress: AA:BB:CC:DD:EE:F4
       hardwareProfile: default
pullSecret: '{...}'
ssh-key: '...'
# proxy:
#   httpProxy: http://<username>:<pswd>@<ip>:<port> 
#   httpsProxy: http://<username>:<pswd>@<ip>:<port> 
#   noProxy: example.com, some.destination.com